### ISSUE TITLE
Add the following commonly used methods

### ISSUE THREAD

**Issue by xbenjii** [ndugger/youdontneedjquery#1]
[find()](http://api.jquery.com/find)
[off()](http://api.jquery.com/off)
[val()](http://api.jquery.com/val)
[css()](http://api.jquery.com/css)
[parents()](http://api.jquery.com/parents)

**Comment by ndugger** [comment]
- done (thought finding from multiple elements is a bit messy)
- done
- done
- done
- done

**Comment by xbenjii** [comment]
Do note that `find` and `parents` both work recursively into their children/parents up and down the DOM tree and can take a parameter to filter out.

**Comment by ndugger** [comment]
I think my "find" version is acceptable as the alternative, but I will have to look more at the "parents" method.
