### ISSUE TITLE
hide--show-element

### ISSUE THREAD

**Issue by rlemon** [ndugger/youdontneedjquery#10]
HTML5 introduced a 'hidden' global attribute https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/hidden 

I think if you're going to be boasting 'new' approaches to things to make them easier you should mention this. It does have virtually no specificity, but it _does_ achieve the same end goal (assuming specificity isn't a concern) and is much nicer to work with vs element.style

**Comment by ndugger** [comment]
Done
